#!/bin/bash

# Set functions
set_vfs_num() {
  echo ${1} > /sys/devices/pci0000:00/0000:00:02.0/sriov_numvfs
}

check_sriov() {
  if modinfo i915 2>/dev/null | grep -qi "sriov" ; then
    exit 0
  else
    exit 1
  fi
}

# Execute functions depending on what was passed over
if [ "$1" == "check" ] ; then
  check_sriov
else
  [ ! -z "$3" ] && \
    set_vfs_num $3
fi
